In [1]:
# Importar bibliotecans necessárias
import os
import glob
import pandas as pd
# Bibliteca responsavel pelos gráficos
import bar_chart_race as bcr

In [2]:
#Caminho do arquivo xlsx
os.chdir('..') #Voltar uma pasta
path = os.path.join(os.getcwd(),r'DADOS')
file = glob.glob(path + '/Modelo.csv')

In [3]:
#Salvar em um dataframe
df = pd.read_csv(file[0],
                 encoding='utf-8',
                 sep=';')

In [4]:
df

,Municípios,1960,1970,1980,1991,2022,2000,2010,2014,2021
0,Cidade Ocidental,-,-,-,-,91767,40377,55915,62903,84581
1,Valparaíso de Goiás,-,-,-,-,198861,94856,132982,150005,196967
2,Cocalzinho de Goiás,-,-,-,-,25016,14626,17407,18871,24018
3,Alto Paraíso de Goiás,-,2775,2725,4122,10298,6143,6885,7328,10414
4,Planaltina,6339,8972,16178,40201,105031,73718,81649,86751,108846
5,Águas Lindas de Goiás,-,-,-,-,225671,105746,159378,182526,208892
6,Cristalina,9172,11600,15977,24937,62249,34116,46580,52235,58940
7,Padre Bernardo,-,8381,15855,16500,34967,21514,27671,30599,34314
8,Barro Alto,10 910,7 236,11 923,9917,10371,8046,8716,9820,11252
9,Alexânia,8113,9390,12116,16472,27008,20047,23814,25805,28690
10,Goianésia,18 377,40 769,32887,43447,73708,48748,59549,64861,73201
11,Cavalcante,6 369,8 258,8 096,8 156,9589,10759,9392,9747,10991
12,Distrito Federal,140164,537492,1176908,1601094,2817068,2051146,2570160,2852372,2923369
13,Pirenópolis,26735,32065,29329,25056,26690,21245,23066,24279,26598
14,Luziânia,27884,32807,92817,207674,208725,141082,174531,191139,196416
15,Formosa,22196,28874,43297,62982,115669,78651,100085,110388,112542
16,Unaí,46306,52303,67885,69612,86619,70033,77565,82298,86867
17,Buritis,-,9810,15429,18417,24034,20396,22737,24169,25223
18,São João d’Aliança,2 003,3489,4342,5127,13984,6745,10257,11771,11275
19,Santo Antônio do Descoberto ...,-,-,-,35509,72134,51897,63248,69000,68654
20,Vila Propício,-,-,-,-,5815,3716,5145,5520,5646
21,Água Fria de Goiás,-,-,-,3976,4954,4469,5090,5451,5546
22,Arinos,-,-,-,-,17272,17327,17674,18210,18526
23,Alvorada do Norte,-,4113,6 056,7364,8446,7751,8084,8499,8412
24,Novo Gama ...,-,-,-,-,103804,74380,95018,104899,97976
25,Cabeceira Grande,-,-,-,-,6627,5920,6453,6818,6485
26,Cabeceiras,3148,4056,4993,6464,7560,6758,7354,7773,7342
27,Abadiânia,8436,7772,9030,9402,17228,11452,15757,17701,15498
28,Flores de Goiás,-,2 274,3 884,5055,13744,5662,12066,13988,11627
29,Mimoso de Goiás,-,-,4046,3750,2614,2801,2685,2723,2572
30,Corumbá de Goiás,13909,18439,20212,19663,10562,9679,10361,10896,9801
31,Simolândia,-,-,4288,5558,5742,6380,6514,6804,5715
32,Niquelândia,15 501,23736,33485,40739,34964,32486,42361,44895,35609
33,Vila Boa,-,-,-,-,4215,3287,4735,5371,3686

In [5]:
#Organizar o DF: 
        #1) Municípios 
        #2) Série Histórica ordenada

df = df[['Municípios',
        '1960',
        '1970',
        '1980',
        '1991',
        '2000',
        '2010',
        '2014',
        '2021',
        '2022'
       ]]

In [6]:
#Criar uma cópia para trabalha-lá
df_copy = df.copy()

In [7]:
"""
Transpor o DataFrame:
1) O Ano ficará como o index do dataframe transposto
2) As colunas ficaram sem nome. Esse problema será tratado mais a frente
"""
df_t = df_copy.T

In [8]:
df_t

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
Municípios,Cidade Ocidental,Valparaíso de Goiás,Cocalzinho de Goiás,Alto Paraíso de Goiás,Planaltina,Águas Lindas de Goiás,Cristalina,Padre Bernardo,Barro Alto,Alexânia,...,Novo Gama ...,Cabeceira Grande,Cabeceiras,Abadiânia,Flores de Goiás,Mimoso de Goiás,Corumbá de Goiás,Simolândia,Niquelândia,Vila Boa
1960,-,-,-,-,6339,-,9172,-,10 910,8113,...,-,-,3148,8436,-,-,13909,-,15 501,-
1970,-,-,-,2775,8972,-,11600,8381,7 236,9390,...,-,-,4056,7772,2 274,-,18439,-,23736,-
1980,-,-,-,2725,16178,-,15977,15855,11 923,12116,...,-,-,4993,9030,3 884,4046,20212,4288,33485,-
1991,-,-,-,4122,40201,-,24937,16500,9917,16472,...,-,-,6464,9402,5055,3750,19663,5558,40739,-
2000,40377,94856,14626,6143,73718,105746,34116,21514,8046,20047,...,74380,5920,6758,11452,5662,2801,9679,6380,32486,3287
2010,55915,132982,17407,6885,81649,159378,46580,27671,8716,23814,...,95018,6453,7354,15757,12066,2685,10361,6514,42361,4735
2014,62903,150005,18871,7328,86751,182526,52235,30599,9820,25805,...,104899,6818,7773,17701,13988,2723,10896,6804,44895,5371
2021,84581,196967,24018,10414,108846,208892,58940,34314,11252,28690,...,97976,6485,7342,15498,11627,2572,9801,5715,35609,3686
2022,91767,198861,25016,10298,105031,225671,62249,34967,10371,27008,...,103804,6627,7560,17228,13744,2614,10562,5742,34964,4215

In [9]:
#Renomear as colunas com os valores da primeira linha. 
#Ao renomear será removido espaços nos nomes dos municípios
df_t = df_t.rename(columns=df_t.iloc[0].str.strip())
#Resolver problemas de formatação do mun São João d'Aliança
df_t = df_t.rename(columns={'São João dAliança':"São João d'Aliança"})

In [10]:
#Remover a primeira linha do dataframe
df_t = df_t.iloc[1:,:]

In [11]:
#Colocar um nome no index
df_t.index.name='Ano'

In [12]:
df_t

,Cidade Ocidental,Valparaíso de Goiás,Cocalzinho de Goiás,Alto Paraíso de Goiás,Planaltina,Águas Lindas de Goiás,Cristalina,Padre Bernardo,Barro Alto,Alexânia,...,Novo Gama,Cabeceira Grande,Cabeceiras,Abadiânia,Flores de Goiás,Mimoso de Goiás,Corumbá de Goiás,Simolândia,Niquelândia,Vila Boa
Ano,,,,,,,,,,,,,,,,,,,,,
1960,-,-,-,-,6339,-,9172,-,10 910,8113,...,-,-,3148,8436,-,-,13909,-,15 501,-
1970,-,-,-,2775,8972,-,11600,8381,7 236,9390,...,-,-,4056,7772,2 274,-,18439,-,23736,-
1980,-,-,-,2725,16178,-,15977,15855,11 923,12116,...,-,-,4993,9030,3 884,4046,20212,4288,33485,-
1991,-,-,-,4122,40201,-,24937,16500,9917,16472,...,-,-,6464,9402,5055,3750,19663,5558,40739,-
2000,40377,94856,14626,6143,73718,105746,34116,21514,8046,20047,...,74380,5920,6758,11452,5662,2801,9679,6380,32486,3287
2010,55915,132982,17407,6885,81649,159378,46580,27671,8716,23814,...,95018,6453,7354,15757,12066,2685,10361,6514,42361,4735
2014,62903,150005,18871,7328,86751,182526,52235,30599,9820,25805,...,104899,6818,7773,17701,13988,2723,10896,6804,44895,5371
2021,84581,196967,24018,10414,108846,208892,58940,34314,11252,28690,...,97976,6485,7342,15498,11627,2572,9801,5715,35609,3686
2022,91767,198861,25016,10298,105031,225671,62249,34967,10371,27008,...,103804,6627,7560,17228,13744,2614,10562,5742,34964,4215

In [13]:
#Remover caracteres especiais
df_t = df_t.replace(
    {
        "-":"",
        " ":""
    },
    regex=True

)
df_t

,Cidade Ocidental,Valparaíso de Goiás,Cocalzinho de Goiás,Alto Paraíso de Goiás,Planaltina,Águas Lindas de Goiás,Cristalina,Padre Bernardo,Barro Alto,Alexânia,...,Novo Gama,Cabeceira Grande,Cabeceiras,Abadiânia,Flores de Goiás,Mimoso de Goiás,Corumbá de Goiás,Simolândia,Niquelândia,Vila Boa
Ano,,,,,,,,,,,,,,,,,,,,,
1960,,,,,6339,,9172,,10910,8113,...,,,3148,8436,,,13909,,15501,
1970,,,,2775,8972,,11600,8381,7236,9390,...,,,4056,7772,2274,,18439,,23736,
1980,,,,2725,16178,,15977,15855,11923,12116,...,,,4993,9030,3884,4046,20212,4288,33485,
1991,,,,4122,40201,,24937,16500,9917,16472,...,,,6464,9402,5055,3750,19663,5558,40739,
2000,40377,94856,14626,6143,73718,105746,34116,21514,8046,20047,...,74380,5920,6758,11452,5662,2801,9679,6380,32486,3287
2010,55915,132982,17407,6885,81649,159378,46580,27671,8716,23814,...,95018,6453,7354,15757,12066,2685,10361,6514,42361,4735
2014,62903,150005,18871,7328,86751,182526,52235,30599,9820,25805,...,104899,6818,7773,17701,13988,2723,10896,6804,44895,5371
2021,84581,196967,24018,10414,108846,208892,58940,34314,11252,28690,...,97976,6485,7342,15498,11627,2572,9801,5715,35609,3686
2022,91767,198861,25016,10298,105031,225671,62249,34967,10371,27008,...,103804,6627,7560,17228,13744,2614,10562,5742,34964,4215

In [14]:
df_t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 1960 to 2022
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Cidade Ocidental             9 non-null      object
 1   Valparaíso de Goiás          9 non-null      object
 2   Cocalzinho de Goiás          9 non-null      object
 3   Alto Paraíso de Goiás        9 non-null      object
 4   Planaltina                   9 non-null      object
 5   Águas Lindas de Goiás        9 non-null      object
 6   Cristalina                   9 non-null      object
 7   Padre Bernardo               9 non-null      object
 8   Barro Alto                   9 non-null      object
 9   Alexânia                     9 non-null      object
 10  Goianésia                    9 non-null      object
 11  Cavalcante                   9 non-null      object
 12  Distrito Federal             9 non-null      object
 13  Pirenópolis                  9 non-null      object
 14  Luziânia                     9 non-null      object
 15  Formosa                      9 non-null      object
 16  Unaí                         9 non-null      object
 17  Buritis                      9 non-null      object
 18  São João d’Aliança           9 non-null      object
 19  Santo Antônio do Descoberto  9 non-null      object
 20  Vila Propício                9 non-null      object
 21  Água Fria de Goiás           9 non-null      object
 22  Arinos                       9 non-null      object
 23  Alvorada do Norte            9 non-null      object
 24  Novo Gama                    9 non-null      object
 25  Cabeceira Grande             9 non-null      object
 26  Cabeceiras                   9 non-null      object
 27  Abadiânia                    9 non-null      object
 28  Flores de Goiás              9 non-null      object
 29  Mimoso de Goiás              9 non-null      object
 30  Corumbá de Goiás             9 non-null      object
 31  Simolândia                   9 non-null      object
 32  Niquelândia                  9 non-null      object
 33  Vila Boa                     9 non-null      object
dtypes: object(34)
memory usage: 2.5+ KB

In [15]:
#Transformar os valores para numéricos
df_t = df_t.apply(pd.to_numeric)

In [16]:
df_t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 1960 to 2022
Data columns (total 34 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Cidade Ocidental             5 non-null      float64
 1   Valparaíso de Goiás          5 non-null      float64
 2   Cocalzinho de Goiás          5 non-null      float64
 3   Alto Paraíso de Goiás        8 non-null      float64
 4   Planaltina                   9 non-null      int64
 5   Águas Lindas de Goiás        5 non-null      float64
 6   Cristalina                   9 non-null      int64
 7   Padre Bernardo               8 non-null      float64
 8   Barro Alto                   9 non-null      int64
 9   Alexânia                     9 non-null      int64
 10  Goianésia                    9 non-null      int64
 11  Cavalcante                   9 non-null      int64
 12  Distrito Federal             9 non-null      int64
 13  Pirenópolis                  9 non-null      int64
 14  Luziânia                     9 non-null      int64
 15  Formosa                      9 non-null      int64
 16  Unaí                         9 non-null      int64
 17  Buritis                      8 non-null      float64
 18  São João d’Aliança           9 non-null      int64
 19  Santo Antônio do Descoberto  6 non-null      float64
 20  Vila Propício                5 non-null      float64
 21  Água Fria de Goiás           6 non-null      float64
 22  Arinos                       5 non-null      float64
 23  Alvorada do Norte            8 non-null      float64
 24  Novo Gama                    5 non-null      float64
 25  Cabeceira Grande             5 non-null      float64
 26  Cabeceiras                   9 non-null      int64
 27  Abadiânia                    9 non-null      int64
 28  Flores de Goiás              8 non-null      float64
 29  Mimoso de Goiás              7 non-null      float64
 30  Corumbá de Goiás             9 non-null      int64
 31  Simolândia                   7 non-null      float64
 32  Niquelândia                  9 non-null      int64
 33  Vila Boa                     5 non-null      float64
dtypes: float64(18), int64(16)
memory usage: 2.5+ KB

In [17]:
#Com o Distrito Federal
df_tComDF = df_t 
#Sem o Distrito Federal
df_tSemDF = df_t[['Cidade Ocidental', 'Valparaíso de Goiás', 'Cocalzinho de Goiás', 'Alto Paraíso de Goiás',
 'Planaltina', 'Águas Lindas de Goiás', 'Cristalina', 'Padre Bernardo', 'Barro Alto', 'Alexânia', 
 'Goianésia', 'Cavalcante',  'Pirenópolis', 'Luziânia', 'Formosa', 'Unaí', 'Buritis', "São João d’Aliança",
 'Santo Antônio do Descoberto', 'Vila Propício', 'Água Fria de Goiás', 'Arinos', 'Alvorada do Norte', 'Novo Gama',
 'Cabeceira Grande', 'Cabeceiras', 'Abadiânia', 'Flores de Goiás', 'Mimoso de Goiás', 'Corumbá de Goiás',
 'Simolândia', 'Niquelândia', 'Vila Boa']]

In [18]:
#Funções com parâmetros para melhorar visualização do gráfico
def summary(values, ranks):
    total_habitantes = values.sum()
    s = f"Total de habitantes: {total_habitantes:_.0f}"
    s = s.replace('.',',').replace('_','.')
    return {'x': .75, 'y': .05, 's': s, 'size': 8}

def func(values, ranks):
    return values.quantile(.9)

In [19]:
#Com Distrito Federal
bcr.bar_chart_race(df_tComDF,
                   os.path.join(os.getcwd(),'GIF') + '\Crescimento_Populacional_Ride_DF.mp4',
                   steps_per_period=10,
                   perpendicular_bar_func=func, 
                   figsize=(9,7),
                   dpi=288,
                   period_summary_func = summary,
                   period_length=1750, 
                   fixed_max=True)

c:\Users\rogerio.siqueira\Anaconda3\envs\geo_py39\lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(self.df_values.columns)
c:\Users\rogerio.siqueira\Anaconda3\envs\geo_py39\lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))

In [20]:
#Sem Distrito Federal
bcr.bar_chart_race(df_tSemDF,
                   os.path.join(os.getcwd(),'GIF') + '\Crescimento_Populacional_Ride.mp4',
                   steps_per_period=10,
                   perpendicular_bar_func=func, 
                   figsize=(9,7),
                   dpi=288,
                   period_summary_func = summary,
                   period_length=1750, 
                   fixed_max=True)

c:\Users\rogerio.siqueira\Anaconda3\envs\geo_py39\lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(self.df_values.columns)
c:\Users\rogerio.siqueira\Anaconda3\envs\geo_py39\lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))